# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# use default python version for each env
env:
  - TOX_ENV=py-django-18
  - TOX_ENV=py-django-19
  - TOX_ENV=py-django-110

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

notifications:
  email:
    on_success: never
